### ISSUE TITLE
Views should inform about "no data" (e.g. in Workplaces screen)

### ISSUE THREAD

**Issue by dnobel** [iweinzierl/worktrack#23]
When starting the app nearly every Activity is empty. A text should explain the screen and that there is no data currently.

**Comment by iweinzierl** [comment]
Fixed for workplaces: 8357d19a507294e5c5cd0325b57aa102c51e7f84
Fixed for events: 2c20e6b1a079951b58e9ad2413ba83acb6403d0f

**Comment by iweinzierl** [comment]
Open: activity to manage backups.

**Comment by iweinzierl** [comment]
Fixed for backups: 40d3047113c6c2a31186f32d91ca64b72ce04a3d
